name: Build and Push Image, Update Helm Chart

on:
  push:
    branches:
      - 'staging'
      - 'main'

env:
  APP_NAME: staking-api
  K8S_NS: staking
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}

jobs:
  build-and-update:
    name: Build and Push Image, Update Helm Chart
    runs-on: ubuntu-latest

    environment: ${{ (github.ref_name == 'main') && 'production' || 'staging' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
          docker build \
            --push \
            --tag $IMAGE_NAME \
            -f ./Dockerfile \
            .
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: storyprotocol/story-helm
          ref: main
          token: ${{ secrets.CICD_GIT_TOKEN }}
      
      - name: Update Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.image.tag = "${{ github.sha }}"' '${{ env.K8S_NS }}/${{ env.APP_NAME }}/${{ env.CLUSTER_NAME }}.yaml'

      - name: Push Changed Image Tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout main
      
          # If there's nothing to commit, stop here
          if [ -z "$(git status --porcelain)" ]; then
            echo "Nothing to commit, working directory clean"
            exit 0
          fi
      
          # We'll try up to 3 attempts
          for i in 1 2 3
          do
            echo "Attempt #$i to commit and push changes..."
            # Commit if there's something to commit
            git commit -am "${{ env.APP_NAME }}: Update image tag to ${{ github.sha }}"
      
            if git push
            then
              echo "Push succeeded on attempt #$i!"
              break
            else
              echo "Push failed (attempt #$i). Trying to pull and rebase with origin/main."
              git fetch origin main
              git pull --rebase origin main || (echo "Rebase failed!" && exit 1)
            fi
      
            # If this was the last attempt, fail the job
            if [ "$i" -eq "3" ]
            then
              echo "Exceeded max number of push attempts."
              exit 1
            fi
          done
